In [1]:
import pandas as pd

In [2]:
# reading in the datasets

wine_data = pd.read_csv("winequality-red.csv", sep=";")

In [ ]:
wine_data.head()

### Simple feature Scaling

In [ ]:
# feature by feature
wine_data["fixed acidity"] = wine_data["fixed acidity"] / wine_data["fixed acidity"].max()
wine_data.head()

In [ ]:
# entire dataset
wine_data = wine_data/wine_data.max()
wine_data.head()

### Min-Max Scaling

In [ ]:
# single feature manual

wine_data["fixed acidity"] = (wine_data["fixed acidity"] - wine_data["fixed acidity"].min()) / \
                             (wine_data["fixed acidity"].max() - wine_data["fixed acidity"].min())

wine_data.head()

In [ ]:
# using sklearn

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

wine_data[wine_data.columns] = scaler.fit_transform(wine_data[wine_data.columns])

In [ ]:
wine_data.head()

### Z-Score Normalization

In [3]:
# single feature manual

wine_data["fixed acidity"] = (wine_data["fixed acidity"] - wine_data["fixed acidity"].mean()) / \
                             (wine_data["fixed acidity"].std())
wine_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528194,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,-0.298454,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,-0.298454,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,1.654339,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,-0.528194,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
# using sklearn

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

wine_data[wine_data.columns] = scaler.fit_transform(wine_data[wine_data.columns])

In [5]:
wine_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,-0.787823
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777,-0.787823
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777,-0.787823
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777,0.450848
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246,-0.787823
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,1.542054,-0.075043,-0.978765,0.899886,-0.461180,0.072294,-0.787823
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,2.211469,0.137820,-0.862162,1.353436,0.601055,0.729364,0.450848
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,1.255161,-0.196679,-0.533554,0.705508,0.542042,0.541630,0.450848
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,1.542054,-0.075043,-0.676657,1.677400,0.305990,-0.209308,-0.787823
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,0.203223,-0.135861,-0.666057,0.511130,0.010924,0.541630,0.450848